/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/QnA copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LogoWall: typeof import('./components/LogoWall.vue')['default']
    'Q&A': typeof import('./components/Q&A.vue')['default']
    QnA: typeof import('./components/QnA.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
