import './vmd-app.component'
import './components/vmd-search.component'
import './components/tuf-workshop-card.component'
import './components/tuf-workshop-metadata.component'
import './components/tuf-commune-or-departement-selector.component'
import './components/tuf-button-switch.component'
import './components/tuf-input-range-with-tooltip.component'
import './components/tuf-toggle-switch.component'
