import './vmd-app.component'
import './components/vmd-search.component'
import './components/vmd-appointment-card.component'
import './components/tuf-workshop-metadata.component'
import './components/vmd-commune-or-departement-selector.component'
import './components/vmd-button-switch.component'
import './components/vmd-input-range-with-tooltip.component'
import './components/tuf-toggle-switch.component'
